// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: Public.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PublicServiceClient is the client API for PublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicServiceClient interface {
	CreatePublic(ctx context.Context, in *CreatePublicRequest, opts ...grpc.CallOption) (*VoidPublicResponse, error)
	GetByIdPublic(ctx context.Context, in *ByIdPublicRequest, opts ...grpc.CallOption) (*GetPublicResponse, error)
	GetAllPublic(ctx context.Context, in *FilterPublicRequest, opts ...grpc.CallOption) (*GetAllPublicResponse, error)
	UpdatePublic(ctx context.Context, in *GetPublicResponse, opts ...grpc.CallOption) (*VoidPublicResponse, error)
	DeletePublic(ctx context.Context, in *ByIdPublicRequest, opts ...grpc.CallOption) (*VoidPublicResponse, error)
}

type publicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicServiceClient(cc grpc.ClientConnInterface) PublicServiceClient {
	return &publicServiceClient{cc}
}

func (c *publicServiceClient) CreatePublic(ctx context.Context, in *CreatePublicRequest, opts ...grpc.CallOption) (*VoidPublicResponse, error) {
	out := new(VoidPublicResponse)
	err := c.cc.Invoke(ctx, "/voting.PublicService/CreatePublic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) GetByIdPublic(ctx context.Context, in *ByIdPublicRequest, opts ...grpc.CallOption) (*GetPublicResponse, error) {
	out := new(GetPublicResponse)
	err := c.cc.Invoke(ctx, "/voting.PublicService/GetByIdPublic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) GetAllPublic(ctx context.Context, in *FilterPublicRequest, opts ...grpc.CallOption) (*GetAllPublicResponse, error) {
	out := new(GetAllPublicResponse)
	err := c.cc.Invoke(ctx, "/voting.PublicService/GetAllPublic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) UpdatePublic(ctx context.Context, in *GetPublicResponse, opts ...grpc.CallOption) (*VoidPublicResponse, error) {
	out := new(VoidPublicResponse)
	err := c.cc.Invoke(ctx, "/voting.PublicService/UpdatePublic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) DeletePublic(ctx context.Context, in *ByIdPublicRequest, opts ...grpc.CallOption) (*VoidPublicResponse, error) {
	out := new(VoidPublicResponse)
	err := c.cc.Invoke(ctx, "/voting.PublicService/DeletePublic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicServiceServer is the server API for PublicService service.
// All implementations must embed UnimplementedPublicServiceServer
// for forward compatibility
type PublicServiceServer interface {
	CreatePublic(context.Context, *CreatePublicRequest) (*VoidPublicResponse, error)
	GetByIdPublic(context.Context, *ByIdPublicRequest) (*GetPublicResponse, error)
	GetAllPublic(context.Context, *FilterPublicRequest) (*GetAllPublicResponse, error)
	UpdatePublic(context.Context, *GetPublicResponse) (*VoidPublicResponse, error)
	DeletePublic(context.Context, *ByIdPublicRequest) (*VoidPublicResponse, error)
	mustEmbedUnimplementedPublicServiceServer()
}

// UnimplementedPublicServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPublicServiceServer struct {
}

func (UnimplementedPublicServiceServer) CreatePublic(context.Context, *CreatePublicRequest) (*VoidPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePublic not implemented")
}
func (UnimplementedPublicServiceServer) GetByIdPublic(context.Context, *ByIdPublicRequest) (*GetPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdPublic not implemented")
}
func (UnimplementedPublicServiceServer) GetAllPublic(context.Context, *FilterPublicRequest) (*GetAllPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPublic not implemented")
}
func (UnimplementedPublicServiceServer) UpdatePublic(context.Context, *GetPublicResponse) (*VoidPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePublic not implemented")
}
func (UnimplementedPublicServiceServer) DeletePublic(context.Context, *ByIdPublicRequest) (*VoidPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePublic not implemented")
}
func (UnimplementedPublicServiceServer) mustEmbedUnimplementedPublicServiceServer() {}

// UnsafePublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicServiceServer will
// result in compilation errors.
type UnsafePublicServiceServer interface {
	mustEmbedUnimplementedPublicServiceServer()
}

func RegisterPublicServiceServer(s grpc.ServiceRegistrar, srv PublicServiceServer) {
	s.RegisterService(&PublicService_ServiceDesc, srv)
}

func _PublicService_CreatePublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).CreatePublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.PublicService/CreatePublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).CreatePublic(ctx, req.(*CreatePublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_GetByIdPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByIdPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).GetByIdPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.PublicService/GetByIdPublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).GetByIdPublic(ctx, req.(*ByIdPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_GetAllPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).GetAllPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.PublicService/GetAllPublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).GetAllPublic(ctx, req.(*FilterPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_UpdatePublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).UpdatePublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.PublicService/UpdatePublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).UpdatePublic(ctx, req.(*GetPublicResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_DeletePublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByIdPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).DeletePublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.PublicService/DeletePublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).DeletePublic(ctx, req.(*ByIdPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicService_ServiceDesc is the grpc.ServiceDesc for PublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voting.PublicService",
	HandlerType: (*PublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePublic",
			Handler:    _PublicService_CreatePublic_Handler,
		},
		{
			MethodName: "GetByIdPublic",
			Handler:    _PublicService_GetByIdPublic_Handler,
		},
		{
			MethodName: "GetAllPublic",
			Handler:    _PublicService_GetAllPublic_Handler,
		},
		{
			MethodName: "UpdatePublic",
			Handler:    _PublicService_UpdatePublic_Handler,
		},
		{
			MethodName: "DeletePublic",
			Handler:    _PublicService_DeletePublic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Public.proto",
}
